library(sf)
library(dplyr)
library(readr)
library(raster)
library(sf)
# library(lwgeom)
# library(raster)
# library(sp)
# library(gdistance)
# library(stars)
# library(plyr)
# library(dplyr)
# library(foreach)
# library(doSNOW)
# library(stars)
# library(iterators)
# library(LearnGeom)
# library(tmap)
# library(viridis)
# library(shinyjs)
# library(formatR)
# library(tidyr)
# library(fasterize)
# library(randomForest)
# #library (here)
# library (reshape)
# library (ggplot2)
# library(scales)
# library(data.table)
# library(clhs)
# library(caret)
# library(tictoc)
library(mapview)
# library (doParallel)
#install.packages("mapview")

TmpDir <- 'tmp'
OutDir <- 'outputs'
DataDir <- 'inputs'
dataOutDir <- file.path(OutDir,'inputs')
tileOutDir <- file.path(dataOutDir,'tile')

dir.create(TmpDir, showWarnings = FALSE)
dir.create(OutDir, showWarnings = FALSE)
dir.create(DataDir, showWarnings = FALSE)
dir.create(file.path(dataOutDir), showWarnings = FALSE)
dir.create(file.path(tileOutDir), showWarnings = FALSE)

